# Aula 77

In [5]:
import numpy as np

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x, y = np.arange(10).reshape((5,2)), range(5)

In [11]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
list(y)

[0, 1, 2, 3, 4]

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [15]:
x_train

array([[8, 9],
       [2, 3],
       [4, 5]])

In [16]:
y_train

[4, 1, 2]

In [17]:
x_test

array([[0, 1],
       [6, 7]])

In [18]:
y_test

[0, 3]

In [19]:
model.fit(x_train, y_train)

NameError: name 'model' is not defined