##  NumPy indexação e Seleção

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[8]

8

In [16]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [18]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr[0:5] = 100

In [20]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
slice_of_arr = arr[0:6]

In [22]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [24]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[0,1]

10

In [31]:
arr_2d = np.arange(50).reshape(5,10)

In [32]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_2d[1:3,2:4]

array([[12, 13],
       [22, 23]])